config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories
  resources :tasks
  resources :users, only: [:create]

  get '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :task, dependent: :destroy
    belongs_to :user

    
    validates :category_name, presence: true, uniqueness: true
    validates :category_details, :user_id, presence: true

    def task_count
        task.count
    end

end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category

    
    validates :task_name, presence: true, uniqueness: true
    validates :task_details, :category_id, :deadline, presence: true

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :categories, dependent: :destroy

    validates :username, presence: true, uniqueness: true
    validates :password_digest, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def authenticate_user!
    redirect_to login_path unless current_user
  end

  def current_user
    @current_user ||=
      begin
        return nil unless session[:user_id]

        User.find(session[:user_id])
      end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.includes(:task)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @tasks = @category.task
  end

  # GET /categories/new
  def new
    @category = current_user.categories.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name, :category_details, :user_id)
    end

    def require_login
    unless current_user
      redirect_to login_path, notice: 'You need to log in to access that page!'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Login successful!'
    else
      # flash.now[:notice] = 'Invalid username or password'
      redirect_to login_path, notice: 'Invalid username or password'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out successfully!'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :check_category_count, only: %i[new create edit update show]
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_categories, only: %i[new create edit update]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.includes(:category).all
    @tasks_due_today = Task.where("deadline = ?", Date.today)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    # @category = @task.category
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_name, :task_details, :is_finished, :deadline, :category_id)
    end
    
    def set_categories
      @categories = Category.all
    end

    def check_category_count
      if Category.count.zero?
        redirect_to new_category_path, notice: "Categories count is 0.Create a category first!"
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, notice: 'User successfully registered!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="max-w-sm p-6 bg-violet-200 border border-gray-200 rounded-lg shadow m-4">
  <% if action_name == "show" %>
    <label class="my-8 font-black text-3xl">Category Information</label>
  <% end %>
  
  <p class="my-5 flex flex-col items-center text-center w-full">
    <strong class="font-bold text-xl mb-1">Category name:</strong>
    <%= category.category_name %>
  </p>

  <p class="my-5 flex flex-col items-center text-center w-full">
    <strong class="font-bold text-xl mb-1">Category details:</strong>
    <%= category.category_details %>
  </p>

  <p class="my-5 flex flex-col items-center text-center w-full">
    <strong class="font-bold text-xl mb-1">Owner:</strong>
    <%= category.user.username %>
  </p>
  <div class="flex flex-col items-center w-full">
    <% if action_name != "show" %>
      <p class="w-full text-center">(<%= category.task_count %> task/s)</p>
      <%= link_to "Show this category", category, class: "mt-3 px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300" %>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :category_name %>
    <%= form.text_field :category_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_details %>
    <%= form.text_area :category_details, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5 hidden">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", value: current_user.id %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/index.html.erb
<div class="w-screen h-full flex flex-col items-center">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg" id="notice"><%= notice %></p>
  <% end %>

  <div class="w-4/5 flex flex-col items-center mt-6">
    <label class="font-bold text-4xl">Categories</label>
    <%= link_to "+", new_category_path, class: "rounded-full py-1 px-3 bg-blue-600 text-white font-medium text-3xl mt-2" %>
    <div id="categories" class="w-full m-2 flex flex-wrap">
      <%= render @categories %>
    </div>
  </div>

</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  
  <% if notice.present? %>
    <p class="py-2 px-3 mb-5 text-red-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/categories/show.html.erb
<div class="w-full flex flex-col items-center justify-center">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @category %>
    <label class="font-bold text-xl my-2">Tasks in this Category</label>
  <% if @category.task_count == 0 %>
    <label class="my-2 text-slate-500 text-3xl">No Task Added in this Category</label>
  <% end %>
    
  <div class="w-full my-5 flex justify-center items-center flex-wrap">
      <% @tasks.each do |task| %>
        <li class="w-1/3 flex flex-col items-center justify-center ">
          <%= link_to task.task_name + ' (' + task.deadline.to_s+')', task, class: "underline py-3 px-5 font-medium" %>
        </li>
      <% end %>
  </div>

      <%= link_to "Add New task", new_task_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium mb-4" %>

    <div class="flex justify-between ml-2 mt-4">
    <%= link_to "Edit this category", edit_category_path(@category), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= button_to "Destroy this category", category_path(@category), method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= link_to "Back to categories", root_path, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-h-screen bg-yellow-100">

<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">My Journal App</span>
    </a>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <a href="/categories" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Categories</a>
        </li>
        <li>
          <%= link_to "Tasks", tasks_path, class:"block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white" %>
        </li>
        <li>
          <% if current_user %>
            <%= button_to 'Log Out', logout_path, method: :delete, class: "text-red-500" %>
          <% else %>
            <%= link_to 'Log In', login_path, class:"text-green-500" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

    <main class="w-screen h-full flex items-center justify-center">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "contents") do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :task_name %>
    <%= form.text_field :task_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :task_details %>
    <%= form.text_area :task_details, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if action_name == "edit" %>
  <div class="my-5">
    <%= form.label :is_finished %>
    <%= form.check_box :is_finished, class: "block mt-2 h-5 w-5" %>
  </div>
  <% end %>

  <div class="my-5">
    <%= form.label :deadline %>
    <%= form.date_field :deadline, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id, @categories, :id, :category_name, prompt: "Select a category") %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="w-96 p-6 bg-pink-200 border border-gray-200 rounded-lg shadow m-4">
  <p class="my-5">
    <strong class="block font-medium mb-1">Task name:</strong>
    <%= task.task_name %>
  </p>

  <% if action_name == "show" %>
    <p class="my-5">
      <strong class="block font-medium mb-1">Task details:</strong>
      <%= task.task_details %>
    </p>

    <p class="my-5">
      <strong class="block font-medium mb-1">Is finished:</strong>
      <%= task.is_finished %>
    </p>  <p class="my-5">
      <strong class="block font-medium mb-1">Category:</strong>
      <%= task.category.category_name %>
    </p>
  <% end %>
  <p class="my-5">
    <strong class="block font-medium mb-1">Deadline:</strong>
    <%= task.deadline %>
  </p>


  <% if action_name != "show" %>
    <%= link_to "Show this task", task, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this task", edit_task_path(task), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Show this task", @task, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/index.html.erb
<div class="w-screen h-full flex flex-col items-center">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="w-4/5 flex flex-col items-center mt-6">
    

    <div class="w-full flex justify-end items-center">
      <%= link_to "New task", new_task_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </div>

    <h1 class="font-bold text-4xl">Tasks Due Today</h1>
    <div id="tasks" class="w-full min-h-96 m-2 flex flex-wrap">
      <%= render @tasks_due_today %>
    </div>

    <label class="font-bold text-3xl mt-4">Tasks List</label>
    <div id="tasks" class="w-full m-2 flex flex-wrap">
      <%= render @tasks %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New task</h1>

  <%= render "form", task: @task %>

  <%= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tasks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex items-center justify-center">
  <div class="w-full flex flex-col items-center justify-center">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <label class="my-8 font-black text-3xl">Task Information</label>
    <%= render @task %>

    <div class="flex justify-between ml-2 mt-4">
      <%= link_to "Edit this task", edit_task_path(@task), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      <%= button_to "Destroy this task", task_path(@task), method: :delete, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    <%= link_to "Back to tasks", tasks_path, class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<%= form_with(model: @user, url: users_path, method: :post, class:"w-1/2 mt-16 py-10 bg-white flex flex-col items-center justify-center") do |form| %>
  <label class="font-bold text-2xl my-2">Sign Up</label>

  <%= form.label :username %>
  <%= form.text_field :username %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit 'Register' %>
<% end %>